# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G


# Base properties
    # minecraft version
    minecraft_version=1.20.1
    # forge version, latest version can be found on https://files.minecraftforge.net/
    forge_version=47.4.0
    mapping_channel=parchment
    mapping_version=2023.09.03

# Mod Properties
    mod_version=2.10.0
    maven_group=net.neganote.gtmutils
    archives_base_name=gtmutils
    mod_id=gtmutils
    mod_name=GregTech Modern Utilities
    mod_url=
    mod_author=NegaNote
    mod_license=LGPLv3.0

# Dependencies
    appeng_version=15.0.18
    architectury_version=9.2.14
    gtceu_version=8.0.0-SNAPSHOT
    mui_version=3.3.1-SNAPSHOT
    registrate_version=MC1.20-1.3.11
    rhino_version=2001.2.3-build.6
    kubejs_version=2001.6.5-build.14
    configuration_version=3.1.0-forge
    jei_version=15.20.0.116
    emi_version = 1.1.24
